import { InjectionToken } from '@angular/core';
import type { App } from './app';
import type { FinanceFacade } from './domains/finance/finance.facade';
import type { MessagesFacade } from './domains/messages/messages.facade';
import type { OrdersListFacade } from './domains/orders/orders-list.facade';
import type { OrdersFacade } from './domains/orders/orders.facade';

export const DASHBOARD_ORDERS_MESSAGES = new InjectionToken<Pick<MessagesFacade,
  "isPostPaymentWhatsAppCandidate"
  | "openPostPaymentWhatsApp"
  | "openWhatsAppReview"
>>('DASHBOARD_ORDERS_MESSAGES');

export const DASHBOARD_ORDERS_SHELL = new InjectionToken<Pick<App,
  "actionBusy"
  | "capitalize"
  | "captureFocus"
  | "formDirty"
  | "activeView"
  | "activeModal"
  | "restoreFocus"
  | "openModal"
  | "errorMessage"
  | "optionalText"
  | "setPendingAction"
  | "editField"
  | "markCopied"
  | "refreshAll"
  | "showToast"
  | "readError"
  | "statusLabel"
>>('DASHBOARD_ORDERS_SHELL');

export const DASHBOARD_ORDERS_FINANCE = new InjectionToken<Pick<FinanceFacade,
  "openPayment"
  | "paymentAmountPaid"
  | "paymentAmountAgreed"
>>('DASHBOARD_ORDERS_FINANCE');

export const DASHBOARD_FINANCE_SHELL = new InjectionToken<Pick<App,
  "activeView"
  | "errorMessage"
  | "readError"
  | "openModal"
  | "setPendingAction"
  | "activeModal"
  | "getSweetAlert"
  | "actionBusy"
  | "refreshAll"
  | "showToast"
  | "formatDate"
  | "formatMoney"
  | "formatPercent"
  | "editField"
  | "statusLabel"
  | "optionalText"
  | "formDirty"
>>('DASHBOARD_FINANCE_SHELL');

export const DASHBOARD_FINANCE_ORDERS = new InjectionToken<Pick<OrdersFacade,
  "selectOrder"
  | "standardPackageAmount"
  | "loadSelectedOrderDetail"
  | "selectedOrderDetail"
  | "requireSelectedOrder"
>>('DASHBOARD_FINANCE_ORDERS');

export const DASHBOARD_MESSAGES_SHELL = new InjectionToken<Pick<App,
  "openModal"
  | "errorMessage"
  | "showToast"
  | "getSweetAlert"
  | "readError"
  | "actionBusy"
  | "refreshAll"
  | "closeModal"
  | "markCopied"
>>('DASHBOARD_MESSAGES_SHELL');

export const DASHBOARD_MESSAGES_ORDERS = new InjectionToken<Pick<OrdersFacade,
  "selectedOrderDetail"
>>('DASHBOARD_MESSAGES_ORDERS');

export const DASHBOARD_CREATE_ORDER_MODAL_SHELL = new InjectionToken<Pick<App,
  "activeModal"
  | "closeModal"
  | "editField"
  | "formDirty"
  | "formatMoney"
>>('DASHBOARD_CREATE_ORDER_MODAL_SHELL');

export const DASHBOARD_CREATE_ORDER_MODAL_ORDERS = new InjectionToken<Pick<OrdersFacade,
  "newDocumentType"
  | "newDocumentNumber"
  | "newPassword"
  | "newContactName"
  | "newContactWhatsapp"
  | "newContactWhatsappUsername"
  | "newContactSource"
  | "newServicePackage"
  | "servicePackages"
  | "servicePackageOptionLabel"
  | "newServicePackageDefinition"
  | "newCustomReservationPrice"
  | "newMinimumReservationDate"
  | "newMaximumReservationDate"
  | "newAllowedWeekdays"
  | "newExcludedDateRanges"
  | "newExcludedDateStart"
  | "newExcludedDateEnd"
  | "addNewExcludedDateRange"
  | "removeNewExcludedDateRange"
  | "clearNewExcludedDateRanges"
  | "requestCreateOrder"
>>('DASHBOARD_CREATE_ORDER_MODAL_ORDERS');

export const DASHBOARD_EDIT_ORDER_MODAL_SHELL = new InjectionToken<Pick<App,
  "activeModal"
  | "closeModal"
  | "statusLabel"
  | "editField"
  | "statusTone"
>>('DASHBOARD_EDIT_ORDER_MODAL_SHELL');

export const DASHBOARD_EDIT_ORDER_MODAL_ORDERS = new InjectionToken<Pick<OrdersFacade,
  "modalOrder"
  | "orderLabel"
  | "editOrderSection"
  | "orderDetailLoading"
  | "contactName"
  | "selectedOrderWhatsappPlaceholder"
  | "contactWhatsapp"
  | "contactWhatsappUsername"
  | "contactSource"
  | "requestContactUpdate"
  | "isClosedOrder"
  | "orderDocumentType"
  | "orderDocumentNumber"
  | "orderPasswordVisible"
  | "orderPassword"
  | "toggleOrderPasswordVisibility"
  | "requestCredentialsUpdate"
  | "orderMinimumReservationDate"
  | "orderMaximumReservationDate"
  | "orderAllowedWeekdays"
  | "orderExcludedDateRanges"
  | "orderExcludedDateStart"
  | "orderExcludedDateEnd"
  | "addOrderExcludedDateRange"
  | "removeOrderExcludedDateRange"
  | "clearOrderExcludedDateRanges"
  | "requestReservationRestrictionsUpdate"
  | "orderPriority"
  | "requestPriorityUpdate"
>>('DASHBOARD_EDIT_ORDER_MODAL_ORDERS');

export const DASHBOARD_EDIT_ORDER_MODAL_FINANCE = new InjectionToken<Pick<FinanceFacade,
  "paymentLabel"
>>('DASHBOARD_EDIT_ORDER_MODAL_FINANCE');

export const DASHBOARD_FINANCE_ENTRY_MODAL_SHELL = new InjectionToken<Pick<App,
  "activeModal"
  | "closeModal"
  | "editField"
>>('DASHBOARD_FINANCE_ENTRY_MODAL_SHELL');

export const DASHBOARD_FINANCE_ENTRY_MODAL_FINANCE = new InjectionToken<Pick<FinanceFacade,
  "editingFinanceEntryId"
  | "financeOccurredOn"
  | "financeEntryKind"
  | "financeCategoryCode"
  | "financeCategories"
  | "financeDataQuality"
  | "financeDescription"
  | "financeVendor"
  | "financeAmountOriginal"
  | "financeCurrency"
  | "financeExchangeRatePen"
  | "financeQuantity"
  | "financeUnit"
  | "financeChannel"
  | "financeCampaign"
  | "financeOrderId"
  | "financeEvidenceReference"
  | "financeNotes"
  | "requestSaveFinanceEntry"
>>('DASHBOARD_FINANCE_ENTRY_MODAL_FINANCE');

export const DASHBOARD_FINANCE_ENTRY_MODAL_ORDERLIST = new InjectionToken<Pick<OrdersListFacade,
  "orders"
>>('DASHBOARD_FINANCE_ENTRY_MODAL_ORDERLIST');

export const DASHBOARD_ORDER_ACTIONS_MODAL_SHELL = new InjectionToken<Pick<App,
  "activeModal"
  | "closeModal"
  | "statusLabel"
  | "actionBusy"
  | "editField"
>>('DASHBOARD_ORDER_ACTIONS_MODAL_SHELL');

export const DASHBOARD_ORDER_ACTIONS_MODAL_ORDERS = new InjectionToken<Pick<OrdersFacade,
  "modalOrder"
  | "orderLabel"
  | "closureDisplay"
  | "requestOrderAction"
  | "hasActiveChildOrders"
  | "isClosedOrder"
  | "requestManualSession"
  | "manualSessionActionLabel"
  | "requestDiagnosticSession"
  | "closureReason"
  | "setClosureReason"
  | "closureNote"
  | "requestCloseOrder"
>>('DASHBOARD_ORDER_ACTIONS_MODAL_ORDERS');

export const DASHBOARD_PAYMENT_MODAL_SHELL = new InjectionToken<Pick<App,
  "activeModal"
  | "closeModal"
  | "formatMoney"
  | "formatDate"
  | "formatTime"
  | "editField"
  | "actionBusy"
>>('DASHBOARD_PAYMENT_MODAL_SHELL');

export const DASHBOARD_PAYMENT_MODAL_ORDERS = new InjectionToken<Pick<OrdersFacade,
  "modalOrder"
  | "orderLabel"
  | "servicePackageDefinition"
  | "standardPackageAmount"
>>('DASHBOARD_PAYMENT_MODAL_ORDERS');

export const DASHBOARD_PAYMENT_MODAL_FINANCE = new InjectionToken<Pick<FinanceFacade,
  "paymentAmountAgreed"
  | "paymentAmountPaid"
  | "setQuickPaymentAmount"
  | "requestMarkPaid"
>>('DASHBOARD_PAYMENT_MODAL_FINANCE');

export const DASHBOARD_WHATSAPP_MODAL_SHELL = new InjectionToken<Pick<App,
  "activeModal"
  | "actionBusy"
  | "closeModal"
  | "statusLabel"
  | "formatDateTime"
  | "statusTone"
>>('DASHBOARD_WHATSAPP_MODAL_SHELL');

export const DASHBOARD_WHATSAPP_MODAL_MESSAGES = new InjectionToken<Pick<MessagesFacade,
  "whatsappTestMode"
  | "whatsappReviewMode"
  | "whatsappFollowUpMode"
  | "whatsappPackage"
  | "whatsappFollowUpPackage"
  | "whatsappTestRecipient"
  | "whatsappFollowUpLoading"
  | "whatsappPackageLoading"
  | "prepareWhatsAppTest"
  | "whatsappReview"
  | "copyWhatsAppText"
  | "whatsappWebBusy"
  | "confirmAndSendWhatsAppFollowUp"
  | "whatsappWebResult"
  | "confirmWhatsAppFollowUpSent"
  | "whatsappReviewNote"
  | "resolveWhatsAppReview"
  | "confirmAndSendWhatsAppEvidence"
  | "whatsappManualFallbackOpen"
  | "copyWhatsAppAttachment"
  | "confirmWhatsAppSent"
>>('DASHBOARD_WHATSAPP_MODAL_MESSAGES');

export const DASHBOARD_WORKER_RESTART_MODAL_SHELL = new InjectionToken<Pick<App,
  "activeModal"
  | "phaseLabel"
  | "worker"
  | "health"
  | "closeModal"
  | "currentWorkLabel"
  | "releaseSafeBackoffsOnRestart"
  | "requestRestartWorker"
>>('DASHBOARD_WORKER_RESTART_MODAL_SHELL');

export const DASHBOARD_PROGRAM_RESOLUTION_PANEL_ORDERS = new InjectionToken<Pick<OrdersFacade,
  "selectedOrderDetail"
  | "requestProgramResolution"
  | "orderDetailLoading"
  | "servicePriceLabel"
  | "restrictionDaysLabel"
  | "restrictionTimingLabel"
  | "openProgramResolution"
>>('DASHBOARD_PROGRAM_RESOLUTION_PANEL_ORDERS');

export const DASHBOARD_PROGRAM_RESOLUTION_PANEL_SHELL = new InjectionToken<Pick<App,
  "formDirty"
  | "errorMessage"
  | "actionBusy"
  | "closeModal"
>>('DASHBOARD_PROGRAM_RESOLUTION_PANEL_SHELL');

export const DASHBOARD_CAPTCHAS_VIEW_SHELL = new InjectionToken<Pick<App,
  "showAllPendingCaptchas"
  | "captchaState"
  | "loadCaptchaData"
  | "captchaSummary"
  | "statusLabel"
  | "captchaReviewTotal"
  | "captchaPendingTotal"
  | "captchaWorkspaceMode"
  | "showCaptchaWorkspace"
  | "captchaTotal"
  | "captchaQuality"
  | "captchaError"
  | "activeCaptchaReview"
  | "captchaReviewPosition"
  | "captchaReviewReasonLabel"
  | "captchaChoiceLabel"
  | "captchaSourceLabel"
  | "captchaReviewMessage"
  | "captchaOrderLabel"
  | "formatDateTime"
  | "captchaChoiceMode"
  | "captchaPredictionOptions"
  | "captchaSuggestionTone"
  | "captchaSavingEventId"
  | "chooseCaptchaPrediction"
  | "saveCaptchaHumanLabel"
  | "captchaDraft"
  | "updateCaptchaDraft"
  | "isObserverCaptcha"
  | "formatMilliseconds"
  | "captchaPredictionTone"
  | "captchaModelLabel"
  | "moveCaptchaReview"
  | "captchaReviewQueue"
  | "applyCaptchaFilters"
  | "captchaSearch"
  | "captchaReviewStatus"
  | "changeCaptchaReviewStatus"
  | "toggleCaptchaHistoryFilters"
  | "captchaActiveFilterCount"
  | "captchaHistoryFiltersOpen"
  | "captchaAgreement"
  | "setCaptchaAgreement"
  | "captchaSource"
  | "changeCaptchaSource"
  | "captchaPortalStatus"
  | "changeCaptchaPortalStatus"
  | "captchaPage"
  | "captchaTotalPages"
  | "captchaEvents"
  | "captchaAgreementTone"
  | "captchaAgreementLabel"
  | "captchaPortalTone"
  | "captchaPortalLabel"
  | "captchaLocalTotalMs"
  | "pendingCaptchaCorrection"
  | "confirmCaptchaCorrection"
  | "cancelCaptchaCorrection"
  | "formatConfidence"
  | "captchaPageSize"
  | "changeCaptchaPageSize"
  | "goToCaptchaPage"
  | "captchaPageNumbers"
  | "captchaQualityState"
  | "captchaQualityError"
  | "loadCaptchaQuality"
  | "captchaDatasetExporting"
  | "exportCaptchaDataset"
  | "captchaQualityBestModel"
  | "captchaQualityAccuracy"
  | "captchaQualityModelTone"
  | "captchaQualityWeeklyModel"
  | "captchaQualityCases"
  | "captchaQualityCaseFilters"
  | "captchaQualityCaseType"
  | "changeCaptchaQualityCaseType"
  | "captchaQualityCaseSummary"
  | "goToCaptchaQualityCasePage"
  | "captchaQualityCasePageNumbers"
>>('DASHBOARD_CAPTCHAS_VIEW_SHELL');

export const DASHBOARD_FINANCE_VIEW_FINANCE = new InjectionToken<Pick<FinanceFacade,
  "selectedMonth"
  | "financeLoading"
  | "changeMonth"
  | "openNewFinanceEntry"
  | "financeSummary"
  | "financeConversionComplete"
  | "financeQuality"
  | "financeReviewIssueCount"
  | "monthlySummary"
  | "missingAcquisitionSourceOrders"
  | "selectedMonthLabel"
  | "openEditFinanceEntryById"
  | "financeResolutionLabel"
  | "financeMismatchPaymentId"
  | "startFinanceMismatchResolution"
  | "financeMismatchResolution"
  | "financeMismatchReason"
  | "cancelFinanceMismatchResolution"
  | "requestReconcileFinancePayment"
  | "financeMonthClosure"
  | "financeClosureOpeningBalance"
  | "financeClosureClosingBalance"
  | "financeClosureNotes"
  | "financeClosureCanReconcile"
  | "financeSelectedMonthIsClosed"
  | "requestSaveFinanceMonthClosure"
  | "financeEntries"
  | "financeKindLabel"
  | "formatOriginalMoney"
  | "openEditFinanceEntry"
  | "requestVoidFinanceEntry"
>>('DASHBOARD_FINANCE_VIEW_FINANCE');

export const DASHBOARD_FINANCE_VIEW_SHELL = new InjectionToken<Pick<App,
  "formatMoney"
  | "formatDateTime"
  | "formatDate"
  | "actionBusy"
  | "statusTone"
>>('DASHBOARD_FINANCE_VIEW_SHELL');

export const DASHBOARD_FOLLOWUPS_VIEW_SHELL = new InjectionToken<Pick<App,
  "appointmentReminderStatus"
  | "postAppointmentPayload"
  | "setPostAppointmentFilter"
  | "choosePostAppointmentSort"
  | "postAppointmentSortDirection"
  | "togglePostAppointmentSortDirection"
  | "statusLabel"
  | "postAppointmentOutcomeDetail"
  | "formatDateTime"
  | "formatDate"
  | "statusTone"
  | "postAppointmentSearch"
  | "setPostAppointmentSearch"
  | "postAppointmentQuickFilters"
  | "postAppointmentFilter"
  | "postAppointmentItems"
  | "paginatedPostAppointmentItems"
  | "postAppointmentItemNumber"
  | "postAppointmentItemLabel"
  | "postAppointmentStageTone"
  | "postAppointmentMessageTone"
  | "isPostAppointmentReviewing"
  | "reviewPostAppointment"
  | "postAppointmentPageStart"
  | "postAppointmentPageEnd"
  | "currentPostAppointmentPage"
  | "postAppointmentTotalPages"
  | "postAppointmentPageSize"
  | "changePostAppointmentPageSize"
  | "goToPostAppointmentPage"
  | "postAppointmentPageNumbers"
>>('DASHBOARD_FOLLOWUPS_VIEW_SHELL');

export const DASHBOARD_INBOX_VIEW_SHELL = new InjectionToken<Pick<App,
  "inboxPendingTotal"
  | "inboxAccessCount"
  | "inboxPausedCount"
  | "inboxPaymentCount"
  | "inboxMessageCount"
  | "inboxOrderTasks"
  | "openInboxOrder"
  | "actionBusy"
  | "runInboxOrderTask"
  | "captchaShadowEnabled"
  | "captchaReviewTotal"
  | "openInboxCaptchaReview"
>>('DASHBOARD_INBOX_VIEW_SHELL');

export const DASHBOARD_MESSAGE_TEMPLATES_VIEW_MESSAGES = new InjectionToken<Pick<MessagesFacade,
  "whatsappMessageTemplates"
>>('DASHBOARD_MESSAGE_TEMPLATES_VIEW_MESSAGES');

export const DASHBOARD_MESSAGE_TEMPLATES_VIEW_SHELL = new InjectionToken<Pick<App,
  "formDirty"
  | "formatDateTime"
>>('DASHBOARD_MESSAGE_TEMPLATES_VIEW_SHELL');

export const DASHBOARD_ORDERS_VIEW_MESSAGES = new InjectionToken<Pick<MessagesFacade,
  "whatsappSessionBusy"
  | "validateWhatsAppSession"
  | "whatsappSessionState"
  | "openWhatsAppEvidenceTest"
  | "openWhatsAppTest"
  | "canPrepareOrderWhatsApp"
  | "whatsappPreparationHint"
  | "openOrderWhatsApp"
  | "canPreparePostPaymentWhatsApp"
  | "postPaymentWhatsAppHint"
  | "openPostPaymentWhatsApp"
>>('DASHBOARD_ORDERS_VIEW_MESSAGES');

export const DASHBOARD_ORDERS_VIEW_ORDERS = new InjectionToken<Pick<OrdersFacade,
  "openCreateOrder"
  | "orderPanelOpen"
  | "selectedOrder"
  | "closeOrderPanel"
  | "preflightLabel"
  | "orderNextAction"
  | "runNextOrderAction"
  | "needsProgramResolution"
  | "openProgramResolution"
  | "needsCredentialCorrection"
  | "openEditOrder"
  | "requestOrderValidation"
  | "requestOrderAction"
  | "hasActiveChildOrders"
  | "requestManualSession"
  | "openOrderActions"
  | "orderDetailLoading"
  | "selectedOrderWhatsapp"
  | "selectedOrderDetail"
  | "openSelectedOrderWhatsapp"
  | "copySelectedOrderWhatsapp"
  | "isClosedOrder"
  | "serviceTypeLabel"
  | "servicePriceLabel"
  | "priorityExplanation"
  | "restrictionDaysLabel"
  | "restrictionTimingLabel"
  | "setQuickPriority"
  | "closureDisplay"
  | "selectedOrderChildren"
  | "selectOrder"
  | "selectedOrderId"
  | "orderStatusDisplay"
  | "runRowPrimaryAction"
  | "rowPrimaryActionLabel"
  | "openManualSessionNow"
>>('DASHBOARD_ORDERS_VIEW_ORDERS');

export const DASHBOARD_ORDERS_VIEW_SHELL = new InjectionToken<Pick<App,
  "statusTone"
  | "statusLabel"
  | "actionBusy"
  | "copiedLabel"
  | "formatDate"
  | "formatTime"
  | "formatDateTime"
>>('DASHBOARD_ORDERS_VIEW_SHELL');

export const DASHBOARD_ORDERS_VIEW_FINANCE = new InjectionToken<Pick<FinanceFacade,
  "openPayment"
  | "paymentLabel"
  | "paymentAmountLabel"
>>('DASHBOARD_ORDERS_VIEW_FINANCE');

export const DASHBOARD_ORDERS_VIEW_ORDERLIST = new InjectionToken<Pick<OrdersListFacade,
  "orderPageStart"
  | "orderPageEnd"
  | "filteredOrders"
  | "orders"
  | "orderQuickFilters"
  | "orderQuickFilter"
  | "setOrderQuickFilter"
  | "orderFilter"
  | "setOrderFilter"
  | "orderSortKey"
  | "chooseOrderSort"
  | "toggleOrderSortDirection"
  | "orderSortDirection"
  | "orderAriaSort"
  | "setOrderSort"
  | "sortIndicator"
  | "paginatedOrders"
  | "hasReservationRestrictions"
  | "currentOrderPage"
  | "orderTotalPages"
  | "orderPageSize"
  | "changeOrderPageSize"
  | "goToOrderPage"
  | "orderPageNumbers"
>>('DASHBOARD_ORDERS_VIEW_ORDERLIST');

export const DASHBOARD_RUNS_VIEW_SHELL = new InjectionToken<Pick<App,
  "workerCommands"
  | "statusTone"
  | "statusLabel"
  | "formatDateTime"
  | "runStatusFilter"
  | "runStatuses"
  | "selectedRunId"
  | "closeRunDetail"
  | "runDetailState"
  | "runDetailError"
  | "selectRun"
  | "selectedRun"
  | "runResultLabel"
  | "runEvidencePaths"
  | "filteredRuns"
>>('DASHBOARD_RUNS_VIEW_SHELL');

export const DASHBOARD_SUMMARY_VIEW_FINANCE = new InjectionToken<Pick<FinanceFacade,
  "selectedMonth"
  | "monthlyLoading"
  | "changeMonth"
  | "monthlySummary"
  | "metricPeriodLabel"
  | "monthlyRevenueComparison"
  | "dailyRevenueWidth"
  | "selectedMonthLabel"
  | "closedMonthRevenueComparison"
  | "paymentLabel"
>>('DASHBOARD_SUMMARY_VIEW_FINANCE');

export const DASHBOARD_SUMMARY_VIEW_SHELL = new InjectionToken<Pick<App,
  "appointmentReminderStatus"
  | "formatDate"
  | "statusLabel"
  | "formatMoney"
  | "formatDateTime"
  | "openOrderFromSummary"
  | "formatTime"
  | "openPaymentFromSummary"
  | "statusTone"
  | "health"
  | "worker"
  | "phaseLabel"
  | "showPendingPayments"
  | "captchaShadowEnabled"
  | "captchaSamplingEnabled"
  | "captchaAuthorityUsesV6"
  | "captchaSamplingEffectiveLimit"
  | "setCaptchaSamplingEnabled"
  | "captchaSamplingSaving"
  | "captchaSamplingLimit"
  | "setCaptchaSamplingLimit"
  | "captchaSamplingEstimatedSeconds"
  | "captchaAuthorityControl"
  | "requestCaptchaAuthorityFallback"
  | "requestCaptchaAuthorityCanary"
  | "captchaSamplingControl"
  | "captchaSamplingDirty"
  | "saveCaptchaSamplingControl"
  | "currentWorkLabel"
  | "currentOrder"
  | "generalObserverActive"
  | "actionBusy"
  | "pendingWorkerControl"
  | "requestWorkerPauseToggle"
  | "openWorkerRestart"
  | "opportunityControlTone"
  | "opportunityControlLabel"
  | "opportunityMaxSessions"
  | "opportunityControl"
  | "opportunityBreakerOpen"
  | "opportunityReasonLabel"
  | "requestResetOpportunityBreaker"
  | "opportunityModeTone"
  | "opportunityModeLabel"
  | "opportunityActionDisabled"
  | "requestOpportunityContextAction"
  | "opportunityActionLabel"
  | "latestOpportunityBurst"
  | "copyDashboardSnapshot"
  | "filteredRuns"
  | "failedRuns"
  | "loadState"
  | "copiedLabel"
>>('DASHBOARD_SUMMARY_VIEW_SHELL');

export const DASHBOARD_SUMMARY_VIEW_ORDERLIST = new InjectionToken<Pick<OrdersListFacade,
  "readyOrders"
  | "filteredOrders"
  | "pendingPaymentOrders"
  | "confirmedOrders"
>>('DASHBOARD_SUMMARY_VIEW_ORDERLIST');

export const DASHBOARD_SHELL_FINANCE = new InjectionToken<Pick<FinanceFacade,
  "monthlySummary"
  | "financeSummary"
  | "selectedMonth"
  | "loadFinanceView"
  | "openPayment"
  | "clearFinanceForm"
>>('DASHBOARD_SHELL_FINANCE');

export const DASHBOARD_SHELL_MESSAGES = new InjectionToken<Pick<MessagesFacade,
  "whatsappMessageTemplates"
  | "loadMessagesView"
  | "openOrderWhatsApp"
  | "openWhatsAppReview"
  | "whatsappPackage"
  | "whatsappFollowUpPackage"
  | "whatsappTestRecipient"
  | "whatsappTestMode"
  | "whatsappFollowUpMode"
  | "whatsappReviewMode"
  | "whatsappReview"
  | "whatsappReviewNote"
  | "whatsappWebResult"
  | "whatsappManualFallbackOpen"
>>('DASHBOARD_SHELL_MESSAGES');

export const DASHBOARD_SHELL_ORDERS = new InjectionToken<Pick<OrdersFacade,
  "closeTrackedManualSessionsWithBeacon"
  | "orderPanelOpen"
  | "closeOrderPanel"
  | "selectedOrderId"
  | "selectOrder"
  | "servicePackageCatalog"
  | "manualSessions"
  | "loadOrdersView"
  | "openEditOrder"
  | "requestOrderValidation"
  | "hydrateSelectedOrderForms"
  | "clearCreateOrderForm"
  | "applyOrders"
  | "manualSessionOrderLabel"
  | "manualSessionTypeLabel"
  | "isManualSessionClosing"
  | "closeManualSession"
  | "handleBeforeUnload"
>>('DASHBOARD_SHELL_ORDERS');

export const DASHBOARD_DOMAIN_VIEW_TOKENS = [DASHBOARD_CREATE_ORDER_MODAL_SHELL, DASHBOARD_CREATE_ORDER_MODAL_ORDERS, DASHBOARD_EDIT_ORDER_MODAL_SHELL, DASHBOARD_EDIT_ORDER_MODAL_ORDERS, DASHBOARD_EDIT_ORDER_MODAL_FINANCE, DASHBOARD_FINANCE_ENTRY_MODAL_SHELL, DASHBOARD_FINANCE_ENTRY_MODAL_FINANCE, DASHBOARD_FINANCE_ENTRY_MODAL_ORDERLIST, DASHBOARD_ORDER_ACTIONS_MODAL_SHELL, DASHBOARD_ORDER_ACTIONS_MODAL_ORDERS, DASHBOARD_PAYMENT_MODAL_SHELL, DASHBOARD_PAYMENT_MODAL_ORDERS, DASHBOARD_PAYMENT_MODAL_FINANCE, DASHBOARD_WHATSAPP_MODAL_SHELL, DASHBOARD_WHATSAPP_MODAL_MESSAGES, DASHBOARD_WORKER_RESTART_MODAL_SHELL, DASHBOARD_PROGRAM_RESOLUTION_PANEL_ORDERS, DASHBOARD_PROGRAM_RESOLUTION_PANEL_SHELL, DASHBOARD_CAPTCHAS_VIEW_SHELL, DASHBOARD_FINANCE_VIEW_FINANCE, DASHBOARD_FINANCE_VIEW_SHELL, DASHBOARD_FOLLOWUPS_VIEW_SHELL, DASHBOARD_INBOX_VIEW_SHELL, DASHBOARD_MESSAGE_TEMPLATES_VIEW_MESSAGES, DASHBOARD_MESSAGE_TEMPLATES_VIEW_SHELL, DASHBOARD_ORDERS_VIEW_MESSAGES, DASHBOARD_ORDERS_VIEW_ORDERS, DASHBOARD_ORDERS_VIEW_SHELL, DASHBOARD_ORDERS_VIEW_FINANCE, DASHBOARD_ORDERS_VIEW_ORDERLIST, DASHBOARD_RUNS_VIEW_SHELL, DASHBOARD_SUMMARY_VIEW_FINANCE, DASHBOARD_SUMMARY_VIEW_SHELL, DASHBOARD_SUMMARY_VIEW_ORDERLIST] as const;
