from __future__ import annotations

from psycopg import Connection


def _create_order_checks_schema(connection: Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS order_checks (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            order_id text NOT NULL REFERENCES service_orders(order_id) ON DELETE CASCADE,
            status text NOT NULL,
            checked_at timestamptz NOT NULL
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_order_checks_order_checked
        ON order_checks(order_id, checked_at DESC)
        """
    )


def _create_observer_window_metrics_schema(connection: Connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS observer_window_metrics (
            metric_date date NOT NULL,
            window_label text NOT NULL,
            source text NOT NULL,
            status text NOT NULL,
            site text NOT NULL DEFAULT '',
            check_count integer NOT NULL DEFAULT 0 CHECK (check_count >= 0),
            error_count integer NOT NULL DEFAULT 0 CHECK (error_count >= 0),
            total_duration_seconds double precision NOT NULL DEFAULT 0
                CHECK (total_duration_seconds >= 0),
            first_seen_at timestamptz NOT NULL,
            last_seen_at timestamptz NOT NULL,
            last_order_id text,
            last_date text,
            last_hour text,
            PRIMARY KEY (metric_date, window_label, source, status, site)
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_observer_window_metrics_date
        ON observer_window_metrics(metric_date DESC, window_label, source)
        """
    )
