from __future__ import annotations

import threading
from collections.abc import Iterable, Iterator
from contextlib import contextmanager
from datetime import datetime, timedelta
from typing import Any

from psycopg import Connection, connect, sql
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb

from appointment_bot.config import Settings, load_settings
from appointment_bot.domain import (
    ClientStateStatus,
    ResultStatus,
    sanitize_details,
)
from appointment_bot.services.database_models import (
    Client,
    ClientSummary,
    RunDetail,
    RunRecord,
    RunSummary,
    WorkerState,
)
from appointment_bot.utils.sanitization import sanitize_text

SCHEMA_VERSION = 3
_INITIALIZED_URLS: set[str] = set()
_INITIALIZATION_LOCK = threading.Lock()


def init_database(settings: Settings | None = None) -> None:
    settings = _settings(settings)
    database_url = _database_url(settings)
    if database_url in _INITIALIZED_URLS:
        return

    with _INITIALIZATION_LOCK:
        if database_url in _INITIALIZED_URLS:
            return
        with _connection(database_url) as connection:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS schema_version (
                    id integer PRIMARY KEY CHECK (id = 1),
                    version integer NOT NULL
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS clients (
                    client_id text PRIMARY KEY,
                    name text NOT NULL,
                    username text NOT NULL,
                    password text NOT NULL,
                    priority integer NOT NULL DEFAULT 0,
                    active boolean NOT NULL DEFAULT true,
                    done boolean NOT NULL DEFAULT false,
                    created_at text NOT NULL,
                    updated_at text NOT NULL
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS client_state (
                    client_id text PRIMARY KEY REFERENCES clients(client_id) ON DELETE CASCADE,
                    last_status text,
                    last_message text,
                    consecutive_errors integer NOT NULL DEFAULT 0,
                    next_allowed_at text,
                    last_run_at text,
                    last_success_at text,
                    programmed_at text
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS runs (
                    run_id text PRIMARY KEY,
                    client_id text REFERENCES clients(client_id) ON DELETE SET NULL,
                    status text NOT NULL,
                    message text NOT NULL,
                    exit_code integer NOT NULL,
                    started_at text NOT NULL,
                    finished_at text NOT NULL,
                    duration_seconds double precision NOT NULL,
                    reservation_attempted boolean NOT NULL DEFAULT false,
                    reservation_confirmed boolean NOT NULL DEFAULT false,
                    details_json jsonb,
                    screenshot_path text,
                    created_at text NOT NULL
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS run_screenshots (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    run_id text NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
                    path text NOT NULL,
                    created_at text NOT NULL
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS worker_state (
                    id integer PRIMARY KEY CHECK (id = 1),
                    phase text NOT NULL DEFAULT 'stopped',
                    paused boolean NOT NULL DEFAULT false,
                    current_client_id text,
                    masked_account text,
                    session_started_at text,
                    last_check_at text,
                    next_check_at text,
                    confirmed_reservations integer NOT NULL DEFAULT 0,
                    consecutive_errors integer NOT NULL DEFAULT 0,
                    last_error text,
                    availability_signature text,
                    owner_token text,
                    updated_at text NOT NULL
                )
                """
            )
            connection.execute(
                "INSERT INTO worker_state (id, updated_at) VALUES (1, %s) ON CONFLICT DO NOTHING",
                (_now(),),
            )
            connection.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_clients_queue
                    ON clients(active, done, priority DESC, created_at ASC)
                """
            )
            connection.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_runs_client_started
                    ON runs(client_id, started_at DESC)
                """
            )
            _migrate_database(connection)
        _INITIALIZED_URLS.add(database_url)


def add_client(
    client_id: str,
    name: str,
    username: str,
    password: str,
    priority: int,
    *,
    settings: Settings | None = None,
) -> None:
    settings = _settings(settings)
    init_database(settings)
    now = _now()
    with _connection(_database_url(settings)) as connection:
        connection.execute(
            """
            INSERT INTO clients (
                client_id, name, username, password, priority, active, done, created_at, updated_at
            )
            VALUES (%s, %s, %s, %s, %s, true, false, %s, %s)
            ON CONFLICT(client_id) DO UPDATE SET
                name = excluded.name,
                username = excluded.username,
                password = excluded.password,
                priority = excluded.priority,
                active = true,
                done = false,
                updated_at = excluded.updated_at
            """,
            (client_id, name, username, password, priority, now, now),
        )
        connection.execute(
            "INSERT INTO client_state (client_id) VALUES (%s) ON CONFLICT DO NOTHING",
            (client_id,),
        )
        connection.execute(
            """
            UPDATE client_state
            SET last_status = NULL,
                last_message = NULL,
                consecutive_errors = 0,
                next_allowed_at = NULL,
                programmed_at = NULL
            WHERE client_id = %s
            """,
            (client_id,),
        )


def list_clients(settings: Settings | None = None) -> list[Client]:
    settings = _settings(settings)
    init_database(settings)
    with _connection(_database_url(settings)) as connection:
        rows = connection.execute(
            """
            SELECT client_id, name, username, password, priority, active, done,
                   created_at, updated_at
            FROM clients
            ORDER BY priority DESC, created_at ASC
            """
        ).fetchall()
    return [_client_from_row(row) for row in rows]


def list_client_summaries(settings: Settings | None = None) -> list[ClientSummary]:
    settings = _settings(settings)
    init_database(settings)
    with _connection(_database_url(settings)) as connection:
        rows = connection.execute(
            """
            SELECT c.client_id, c.name, c.username, c.priority, c.active, c.done,
                   c.created_at, c.updated_at, s.last_status, s.last_message,
                   COALESCE(s.consecutive_errors, 0) AS consecutive_errors,
                   s.next_allowed_at, s.last_run_at, s.last_success_at, s.programmed_at
            FROM clients c
            LEFT JOIN client_state s ON s.client_id = c.client_id
            ORDER BY c.priority DESC, c.created_at ASC
            """
        ).fetchall()
    return [_client_summary_from_row(row) for row in rows]


def get_client(
    client_id: str,
    *,
    settings: Settings | None = None,
) -> Client | None:
    settings = _settings(settings)
    init_database(settings)
    with _connection(_database_url(settings)) as connection:
        row = connection.execute(
            """
            SELECT client_id, name, username, password, priority, active, done,
                   created_at, updated_at
            FROM clients
            WHERE client_id = %s
            """,
            (client_id,),
        ).fetchone()
    return _client_from_row(row) if row is not None else None


def update_client(
    client_id: str,
    *,
    name: str | None = None,
    username: str | None = None,
    password: str | None = None,
    priority: int | None = None,
    settings: Settings | None = None,
) -> None:
    settings = _settings(settings)
    init_database(settings)
    assignments = []
    values: list[Any] = []
    for field, value in {
        "name": name,
        "username": username,
        "password": password,
        "priority": priority,
    }.items():
        if value is not None:
            assignments.append(f"{field} = %s")
            values.append(value)
    if not assignments:
        return
    assignments.append("updated_at = %s")
    values.append(_now())
    values.append(client_id)
    with _connection(_database_url(settings)) as connection:
        cursor = connection.execute(
            f"UPDATE clients SET {', '.join(assignments)} WHERE client_id = %s",
            values,
        )
        if cursor.rowcount != 1:
            raise ValueError(f"Client not found: {client_id}")


def list_active_clients(settings: Settings | None = None) -> list[Client]:
    settings = _settings(settings)
    init_database(settings)
    with _connection(_database_url(settings)) as connection:
        rows = connection.execute(
            """
            SELECT c.client_id, c.name, c.username, c.password, c.priority,
                   c.active, c.done, c.created_at, c.updated_at
            FROM clients c
            WHERE c.active = true
              AND c.done = false
            ORDER BY c.priority DESC, c.created_at ASC
            """
        ).fetchall()
    return [_client_from_row(row) for row in rows]


def client_backoff_seconds(
    client_id: str,
    *,
    settings: Settings | None = None,
) -> int:
    settings = _settings(settings)
    init_database(settings)
    with _connection(_database_url(settings)) as connection:
        row = connection.execute(
            "SELECT next_allowed_at FROM client_state WHERE client_id = %s",
            (client_id,),
        ).fetchone()

    if row is None or not row["next_allowed_at"]:
        return 0

    try:
        next_allowed_at = datetime.fromisoformat(str(row["next_allowed_at"]))
    except ValueError:
        return 0
    return max(0, int((next_allowed_at - datetime.now()).total_seconds()))


def client_reservation_pending(
    client_id: str,
    *,
    settings: Settings | None = None,
) -> bool:
    settings = _settings(settings)
    init_database(settings)
    with _connection(_database_url(settings)) as connection:
        row = connection.execute(
            "SELECT last_status FROM client_state WHERE client_id = %s",
            (client_id,),
        ).fetchone()
    return row is not None and row["last_status"] in {
        ClientStateStatus.SUBMISSION_INTENT,
        ClientStateStatus.SUBMISSION_PENDING,
        ClientStateStatus.RESERVATION_UNCONFIRMED,
    }


def mark_client_submission_pending(
    client_id: str,
    *,
    settings: Settings | None = None,
) -> None:
    settings = _settings(settings)
    init_database(settings)
    now = _now()
    with _connection(_database_url(settings)) as connection:
        connection.execute(
            """
            INSERT INTO client_state (client_id, last_status, last_message, last_run_at)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT(client_id) DO UPDATE SET
                last_status = excluded.last_status,
                last_message = excluded.last_message,
                last_run_at = excluded.last_run_at,
                next_allowed_at = NULL
            """,
            (
                client_id,
                ClientStateStatus.SUBMISSION_PENDING,
                "Se inicio el envio de una reserva; falta confirmar el resultado.",
                now,
            ),
        )


def mark_client_submission_intent(
    client_id: str,
    *,
    settings: Settings | None = None,
) -> None:
    _set_client_submission_state(
        client_id,
        ClientStateStatus.SUBMISSION_INTENT,
        "Se iniciara el click de reserva; todavia no se confirma su envio.",
        settings=settings,
    )


def clear_client_submission_state(
    client_id: str,
    *,
    settings: Settings | None = None,
) -> None:
    settings = _settings(settings)
    init_database(settings)
    with _connection(_database_url(settings)) as connection:
        connection.execute(
            """
            UPDATE client_state
            SET last_status = NULL,
                last_message = NULL,
                next_allowed_at = NULL
            WHERE client_id = %s
              AND last_status IN (%s, %s, %s)
            """,
            (
                client_id,
                ClientStateStatus.SUBMISSION_INTENT,
                ClientStateStatus.SUBMISSION_PENDING,
                ClientStateStatus.RESERVATION_UNCONFIRMED,
            ),
        )


def client_submission_age_seconds(
    client_id: str,
    *,
    settings: Settings | None = None,
) -> int | None:
    settings = _settings(settings)
    init_database(settings)
    with _connection(_database_url(settings)) as connection:
        row = connection.execute(
            """
            SELECT last_status, last_run_at
            FROM client_state
            WHERE client_id = %s
            """,
            (client_id,),
        ).fetchone()
    if row is None or row["last_status"] not in {
        ClientStateStatus.SUBMISSION_INTENT,
        ClientStateStatus.SUBMISSION_PENDING,
        ClientStateStatus.RESERVATION_UNCONFIRMED,
    }:
        return None
    try:
        started_at = datetime.fromisoformat(str(row["last_run_at"]))
    except (TypeError, ValueError):
        return None
    return max(0, int((datetime.now() - started_at).total_seconds()))


def set_client_active(client_id: str, active: bool, *, settings: Settings | None = None) -> None:
    settings = _settings(settings)
    init_database(settings)
    now = _now()
    with _connection(_database_url(settings)) as connection:
        if active:
            connection.execute(
                """
                UPDATE clients
                SET active = true, done = false, updated_at = %s
                WHERE client_id = %s
                """,
                (now, client_id),
            )
            connection.execute(
                """
                UPDATE client_state
                SET last_status = NULL,
                    last_message = NULL,
                    next_allowed_at = NULL,
                    consecutive_errors = 0,
                    programmed_at = NULL
                WHERE client_id = %s
                """,
                (client_id,),
            )
        else:
            connection.execute(
                "UPDATE clients SET active = false, updated_at = %s WHERE client_id = %s",
                (now, client_id),
            )


def mark_client_done(
    client_id: str,
    *,
    status: str = "registered",
    settings: Settings | None = None,
) -> None:
    settings = _settings(settings)
    init_database(settings)
    now = _now()
    with _connection(_database_url(settings)) as connection:
        connection.execute(
            "UPDATE clients SET done = true, active = false, updated_at = %s WHERE client_id = %s",
            (now, client_id),
        )
        connection.execute(
            """
            INSERT INTO client_state (client_id, programmed_at, last_status, last_run_at)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT(client_id) DO UPDATE SET
                programmed_at = excluded.programmed_at,
                last_status = excluded.last_status,
                last_run_at = excluded.last_run_at,
                next_allowed_at = NULL,
                consecutive_errors = 0
            """,
            (client_id, now, status, now),
        )


def update_client_state(
    client_id: str,
    *,
    status: str,
    message: str,
    exit_code: int,
    backoff_seconds: int | None = None,
    settings: Settings | None = None,
) -> None:
    settings = _settings(settings)
    init_database(settings)
    now = _now()
    next_allowed_at = None
    if backoff_seconds is not None:
        next_allowed_at = (datetime.now() + timedelta(seconds=backoff_seconds)).isoformat(
            timespec="seconds"
        )
    is_error = exit_code != 0 or status in {
        ResultStatus.ERROR,
        ResultStatus.UNKNOWN,
        ResultStatus.RESERVATION_UNCONFIRMED,
    }
    with _connection(_database_url(settings)) as connection:
        connection.execute(
            """
            INSERT INTO client_state (
                client_id, last_status, last_message, consecutive_errors, next_allowed_at,
                last_run_at, last_success_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT(client_id) DO UPDATE SET
                last_status = excluded.last_status,
                last_message = excluded.last_message,
                consecutive_errors = CASE
                    WHEN %s THEN client_state.consecutive_errors + 1
                    ELSE 0
                END,
                next_allowed_at = excluded.next_allowed_at,
                last_run_at = excluded.last_run_at,
                last_success_at = CASE
                    WHEN %s THEN client_state.last_success_at
                    ELSE excluded.last_success_at
                END
            """,
            (
                client_id,
                status,
                sanitize_text(message),
                1 if is_error else 0,
                next_allowed_at,
                now,
                None if is_error else now,
                is_error,
                is_error,
            ),
        )


def create_run_record(
    settings: Settings | None,
    record: RunRecord,
    screenshot_paths: Iterable[str],
) -> None:
    settings = _settings(settings)
    init_database(settings)
    details = Jsonb(sanitize_details(record.details)) if record.details else None
    with _connection(_database_url(settings)) as connection:
        connection.execute(
            """
            INSERT INTO runs (
                run_id, client_id, status, message, exit_code, started_at, finished_at,
                duration_seconds, reservation_attempted, reservation_confirmed, details_json,
                screenshot_path, created_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT(run_id) DO UPDATE SET
                client_id = excluded.client_id,
                status = excluded.status,
                message = excluded.message,
                exit_code = excluded.exit_code,
                started_at = excluded.started_at,
                finished_at = excluded.finished_at,
                duration_seconds = excluded.duration_seconds,
                reservation_attempted = excluded.reservation_attempted,
                reservation_confirmed = excluded.reservation_confirmed,
                details_json = excluded.details_json,
                screenshot_path = excluded.screenshot_path
            """,
            (
                record.run_id,
                record.client_id,
                record.status,
                sanitize_text(record.message),
                record.exit_code,
                record.started_at,
                record.finished_at,
                record.duration_seconds,
                record.reservation_attempted,
                record.reservation_confirmed,
                details,
                record.screenshot_path,
                _now(),
            ),
        )
        connection.execute("DELETE FROM run_screenshots WHERE run_id = %s", (record.run_id,))
        _executemany(
            connection,
            "INSERT INTO run_screenshots (run_id, path, created_at) VALUES (%s, %s, %s)",
            [(record.run_id, path, _now()) for path in screenshot_paths],
        )


def list_runs(
    *,
    limit: int = 50,
    offset: int = 0,
    client_id: str | None = None,
    status: str | None = None,
    settings: Settings | None = None,
) -> list[RunSummary]:
    settings = _settings(settings)
    init_database(settings)
    where, values = _run_filters(client_id=client_id, status=status)
    values.extend([limit, offset])
    with _connection(_database_url(settings)) as connection:
        rows = connection.execute(
            f"""
            SELECT r.run_id, r.client_id, r.status, r.message, r.exit_code, r.started_at,
                   r.finished_at, r.duration_seconds, r.reservation_attempted,
                   r.reservation_confirmed, r.screenshot_path, r.created_at,
                   COUNT(rs.id) AS screenshot_count
            FROM runs r
            LEFT JOIN run_screenshots rs ON rs.run_id = r.run_id
            {where}
            GROUP BY r.run_id
            ORDER BY r.started_at DESC
            LIMIT %s OFFSET %s
            """,
            values,
        ).fetchall()
    return [_run_summary_from_row(row) for row in rows]


def get_run(
    run_id: str,
    *,
    settings: Settings | None = None,
) -> RunDetail | None:
    settings = _settings(settings)
    init_database(settings)
    with _connection(_database_url(settings)) as connection:
        row = connection.execute(
            """
            SELECT r.run_id, r.client_id, r.status, r.message, r.exit_code, r.started_at,
                   r.finished_at, r.duration_seconds, r.reservation_attempted,
                   r.reservation_confirmed, r.details_json, r.screenshot_path, r.created_at,
                   COUNT(rs.id) AS screenshot_count
            FROM runs r
            LEFT JOIN run_screenshots rs ON rs.run_id = r.run_id
            WHERE r.run_id = %s
            GROUP BY r.run_id
            """,
            (run_id,),
        ).fetchone()
        if row is None:
            return None
        screenshot_rows = connection.execute(
            """
            SELECT path
            FROM run_screenshots
            WHERE run_id = %s
            ORDER BY id ASC
            """,
            (run_id,),
        ).fetchall()
    return _run_detail_from_row(row, [str(item["path"]) for item in screenshot_rows])


def get_worker_state(settings: Settings | None = None) -> WorkerState:
    settings = _settings(settings)
    init_database(settings)
    with _connection(_database_url(settings)) as connection:
        row = connection.execute(
            """
            SELECT phase, paused, current_client_id, masked_account,
                   session_started_at, last_check_at, next_check_at,
                   confirmed_reservations, consecutive_errors, last_error,
                   availability_signature, owner_token, updated_at
            FROM worker_state
            WHERE id = 1
            """
        ).fetchone()
    if row is None:
        return WorkerState()
    return WorkerState(
        phase=str(row["phase"]),
        paused=bool(row["paused"]),
        current_client_id=row["current_client_id"],
        masked_account=row["masked_account"],
        session_started_at=row["session_started_at"],
        last_check_at=row["last_check_at"],
        next_check_at=row["next_check_at"],
        confirmed_reservations=int(row["confirmed_reservations"]),
        consecutive_errors=int(row["consecutive_errors"]),
        last_error=row["last_error"],
        availability_signature=row["availability_signature"],
        owner_token=row["owner_token"],
        updated_at=row["updated_at"],
    )


def update_worker_state(
    settings: Settings | None = None,
    *,
    expected_owner_token: str | None = None,
    **changes: Any,
) -> WorkerState:
    settings = _settings(settings)
    init_database(settings)
    allowed = {
        "phase",
        "paused",
        "current_client_id",
        "masked_account",
        "session_started_at",
        "last_check_at",
        "next_check_at",
        "confirmed_reservations",
        "consecutive_errors",
        "last_error",
        "availability_signature",
        "owner_token",
    }
    invalid = set(changes) - allowed
    if invalid:
        raise ValueError(f"Invalid worker state fields: {sorted(invalid)}")
    if not changes:
        return get_worker_state(settings)

    assignments = []
    values = []
    for key, value in changes.items():
        assignments.append(f"{key} = %s")
        values.append(value)
    assignments.append("updated_at = %s")
    values.append(_now())
    values.append(1)
    where = "id = %s"
    if expected_owner_token is not None:
        where += " AND owner_token = %s"
        values.append(expected_owner_token)
    with _connection(_database_url(settings)) as connection:
        cursor = connection.execute(
            f"UPDATE worker_state SET {', '.join(assignments)} WHERE {where}",
            values,
        )
        if expected_owner_token is not None and cursor.rowcount != 1:
            raise RuntimeError("Worker state ownership changed during the update.")
    return get_worker_state(settings)


def cleanup_database_history(
    settings: Settings | None = None,
) -> None:
    settings = _settings(settings)
    init_database(settings)
    cutoff = (datetime.now() - timedelta(days=settings.cleanup_retention_days)).isoformat(
        timespec="seconds"
    )
    with _connection(_database_url(settings)) as connection:
        connection.execute("DELETE FROM runs WHERE created_at < %s", (cutoff,))
        connection.execute(
            """
            DELETE FROM run_screenshots
            WHERE run_id NOT IN (SELECT run_id FROM runs)
            """
        )


def _set_client_submission_state(
    client_id: str,
    status: ClientStateStatus,
    message: str,
    *,
    settings: Settings | None,
) -> None:
    settings = _settings(settings)
    init_database(settings)
    now = _now()
    with _connection(_database_url(settings)) as connection:
        connection.execute(
            """
            INSERT INTO client_state (client_id, last_status, last_message, last_run_at)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT(client_id) DO UPDATE SET
                last_status = excluded.last_status,
                last_message = excluded.last_message,
                last_run_at = excluded.last_run_at,
                next_allowed_at = NULL
            """,
            (client_id, status, message, now),
        )


def _migrate_database(connection: Connection) -> None:
    row = connection.execute("SELECT version FROM schema_version WHERE id = 1").fetchone()
    version = int(row["version"]) if row else 0
    if version < 1:
        version = 1
    if version < 2:
        connection.execute(
            """
            ALTER TABLE worker_state
            ADD COLUMN IF NOT EXISTS owner_token text
            """
        )
        version = 2
    if version < 3:
        _add_check_constraint(
            connection,
            "clients",
            "clients_priority_non_negative",
            "priority >= 0",
        )
        _add_check_constraint(
            connection,
            "clients",
            "clients_not_active_when_done",
            "NOT (active AND done)",
        )
        _add_check_constraint(
            connection,
            "client_state",
            "client_state_known_status",
            """
            last_status IS NULL OR last_status IN (
                'available', 'completed', 'error', 'partial', 'paused', 'registered',
                'reservation_unconfirmed', 'skipped', 'unavailable', 'unknown',
                'programmed', 'submission_intent', 'submission_pending'
            )
            """,
        )
        _add_check_constraint(
            connection,
            "runs",
            "runs_known_status",
            """
            status IN (
                'available', 'completed', 'error', 'partial', 'paused', 'registered',
                'reservation_unconfirmed', 'skipped', 'unavailable', 'unknown'
            )
            """,
        )
        version = 3
    connection.execute(
        """
        INSERT INTO schema_version (id, version)
        VALUES (1, %s)
        ON CONFLICT(id) DO UPDATE SET version = excluded.version
        """,
        (max(version, SCHEMA_VERSION),),
    )


def _settings(settings: Settings | None) -> Settings:
    return settings or load_settings(require_login=False)


def _add_check_constraint(
    connection: Connection,
    table_name: str,
    constraint_name: str,
    expression: str,
) -> None:
    row = connection.execute(
        "SELECT 1 FROM pg_constraint WHERE conname = %s",
        (constraint_name,),
    ).fetchone()
    if row is not None:
        return
    connection.execute(
        sql.SQL("ALTER TABLE {} ADD CONSTRAINT {} CHECK ({})").format(
            sql.Identifier(table_name),
            sql.Identifier(constraint_name),
            sql.SQL(expression),
        )
    )


def _database_url(settings: Settings) -> str:
    if not settings.database_url:
        raise ValueError("APPOINTMENT_DATABASE_URL is required for PostgreSQL.")
    return settings.database_url


@contextmanager
def _connection(database_url: str) -> Iterator[Connection]:
    connection = connect(database_url, row_factory=dict_row)
    try:
        with connection:
            yield connection
    finally:
        connection.close()


def _client_from_row(row: dict[str, Any]) -> Client:
    return Client(
        client_id=str(row["client_id"]),
        name=str(row["name"]),
        username=str(row["username"]),
        password=str(row["password"]),
        priority=int(row["priority"]),
        active=bool(row["active"]),
        done=bool(row["done"]),
        created_at=str(row["created_at"]),
        updated_at=str(row["updated_at"]),
    )


def _client_summary_from_row(row: dict[str, Any]) -> ClientSummary:
    return ClientSummary(
        client_id=str(row["client_id"]),
        name=str(row["name"]),
        username_masked=_mask_username(str(row["username"])),
        priority=int(row["priority"]),
        active=bool(row["active"]),
        done=bool(row["done"]),
        created_at=str(row["created_at"]),
        updated_at=str(row["updated_at"]),
        last_status=row["last_status"],
        last_message=row["last_message"],
        consecutive_errors=int(row["consecutive_errors"]),
        next_allowed_at=row["next_allowed_at"],
        last_run_at=row["last_run_at"],
        last_success_at=row["last_success_at"],
        programmed_at=row["programmed_at"],
    )


def _run_summary_from_row(row: dict[str, Any]) -> RunSummary:
    return RunSummary(
        run_id=str(row["run_id"]),
        client_id=row["client_id"],
        status=str(row["status"]),
        message=sanitize_text(str(row["message"])),
        exit_code=int(row["exit_code"]),
        started_at=str(row["started_at"]),
        finished_at=str(row["finished_at"]),
        duration_seconds=float(row["duration_seconds"]),
        reservation_attempted=bool(row["reservation_attempted"]),
        reservation_confirmed=bool(row["reservation_confirmed"]),
        screenshot_path=_public_path(row["screenshot_path"]),
        screenshot_count=int(row["screenshot_count"]),
        created_at=str(row["created_at"]),
    )


def _run_detail_from_row(row: dict[str, Any], screenshot_paths: list[str]) -> RunDetail:
    summary = _run_summary_from_row(row)
    details = row["details_json"]
    return RunDetail(
        **summary.__dict__,
        details=sanitize_details(details) if isinstance(details, dict) else None,
        screenshot_paths=[
            path for path in (_public_path(item) for item in screenshot_paths) if path is not None
        ],
    )


def _run_filters(*, client_id: str | None, status: str | None) -> tuple[str, list[Any]]:
    filters = []
    values: list[Any] = []
    if client_id:
        filters.append("r.client_id = %s")
        values.append(client_id)
    if status:
        filters.append("r.status = %s")
        values.append(status)
    if not filters:
        return "", values
    return "WHERE " + " AND ".join(filters), values


def _executemany(connection: Connection, query: str, rows: list[tuple[Any, ...]]) -> None:
    if not rows:
        return
    with connection.cursor() as cursor:
        cursor.executemany(query, rows)


def _mask_username(username: str) -> str:
    if not username:
        return ""
    if len(username) <= 3:
        return "***"
    return f"{username[:2]}***{username[-1]}"


def _public_path(value: str | None) -> str | None:
    if not value:
        return None
    return str(value).replace("\\", "/").split("/")[-1]


def _now() -> str:
    return datetime.now().isoformat(timespec="seconds")
